getgenv().Key = "k53208c5a0d62e91a9bf7c99"
getgenv().Config = {
    ["AutoReplay"] = true,
    ["AutoJoinMatch"] = false,
    ["TPLobbyIfPlayer"] = true,
    ["SelectMap"] = "Egg Island",
    ["AutoVoteDifficulty"] = "true",
    ["SelectDifficulty"] = "Nightmare",
    ["SelectMacro"] = "MacroEggNGS",
    ["AutoSkip"] = true,
    ["DeleteMap"] = true,
    ["PlayMacro"] = true,
    ["AutoSave"] = true,
    ["BoostFPS"] = true,
    ["AutoClaimQuest"] = true,
    ["AutoClaimEasterQuest"] = true,
    ["AutoClaimEventsPass"] = true,
    ["AutoClaimVIPRewards"] = true,
    ["WhiteScreen"] = true,
    ["DelayJoin"] = "30",
    ["PlacingFailsafe"] = true,
    ["ExchangeTier"] = "3",
    ["AutoExchangeEgg"] = "true",
    ["MailName"] = "",
    ["RequiredGem"] = 1000,
    ["AutoMail"] = true,
    ["WH_MatchComplete"] = true,
    ["AutoUseBoost"] = true,
    ["UseBoosts"] = {
        ["2xCoinsBoost"] = true,
        ["2xEggsBoost"] = true,
    },
    ["UseAll"] = false,
    ["WebhookURL"] = "https://discord.com/api/webhooks/1218108894107271238/X5rfeL6W4Mxyxj0x5Utz031qk6LwrrbNt4lPIrEdcEMTvT6MdIH97RseBI_EvZYtNKKD",
}
loadstring(game:HttpGet("https://nousigi.com/loader.lua"))()
