getgenv().Key = "k1f0f198eb736efbeea5d9f6"
getgenv().Config = {
    ["AutoReplay"] = true,
    ["AutoJoinMatch"] = true,
    ["TPLobbyIfPlayer"] = true,
    ["SelectMap"] = "Egg Island",
    ["AutoVoteDifficulty"] = "true",
    ["SelectDifficulty"] = "Nightmare",
    ["SelectMacro"] = "MacroEggNGS",
    ["AutoSkip"] = true,
    ["DeleteMap"] = true,
    ["PlayMacro"] = true,
    ["AutoSave"] = true,
    ["BoostFPS"] = true,
    ["AutoClaimQuest"] = true,
    ["AutoClaimEasterQuest"] = true,
    ["AutoClaimEventsPass"] = true,
    ["AutoClaimVIPRewards"] = true,
    ["WhiteScreen"] = false,
    ["DelayJoin"] = "30",
    ["PlacingFailsafe"] = true,
    ["ExchangeTier"] = "3",
    ["AutoExchangeEgg"] = "true",
    ["MailName"] = "",
    ["RequiredGem"] = 1000,
    ["AutoMail"] = true,
    ["WH_MatchComplete"] = true,
    ["AutoUseBoost"] = true,
    ["UseBoosts"] = {
        ["2xCoinsBoost"] = true,
        ["2xEggsBoost"] = true,
    },
    ["UseAll"] = false,
    ["WebhookURL"] = "https://discord.com/api/webhooks/1217899008794558524/sDwbv3gE7C_7uFR-V1LKZeUE0x5bWKT7cmLpo47kBIGZqFKEfrICtrOFuZw03T_J5Dri",
}
loadstring(game:HttpGet("https://nousigi.com/loader.lua"))()
