getgenv().Key = "kb6a970679e83acd52fd6884"
getgenv().Config = {
    ["AutoReplay"] = true,
    ["AutoJoinMatch"] = true,
    ["TPLobbyIfPlayer"] = true,
    ["SelectMap"] = "Egg Island",
    ["AutoVoteDifficulty"] = "true",
    ["SelectDifficulty"] = "Nightmare",
    ["SelectMacro"] = "MacroEggNGS",
    ["AutoSkip"] = true,
    ["DeleteMap"] = true,
    ["PlayMacro"] = true,
    ["AutoSave"] = true,
    ["BoostFPS"] = true,
    ["AutoClaimQuest"] = true,
    ["AutoClaimEasterQuest"] = true,
    ["AutoClaimEventsPass"] = true,
    ["AutoClaimVIPRewards"] = true,
    ["WhiteScreen"] = true,
    ["DelayJoin"] = "30",
    ["PlacingFailsafe"] = true,
    ["ExchangeTier"] = "3",
    ["AutoExchangeEgg"] = "true",
    ["MailName"] = "",
    ["RequiredGem"] = 1000,
    ["AutoMail"] = true,
    ["WH_MatchComplete"] = true,
    ["AutoUseBoost"] = true,
    ["UseBoosts"] = {
        ["2xCoinsBoost"] = true,
        ["2xEggsBoost"] = true,
    },
    ["UseAll"] = false,
    ["WebhookURL"] = "https://discord.com/api/webhooks/1212449694350049330/6vrOV79kMOSTtm4GuhBSOib2u6fT3Gxuy3eSOvGyafVe3H2YR1hRN7RvOTvK1_zVuCy0",
}
loadstring(game:HttpGet("https://nousigi.com/loader.lua"))()
