getgenv().Key = "kc1c453aae8ce9589a7fa6b6"
getgenv().Config = {
    ["AutoReplay"] = true,
    ["AutoJoinMatch"] = true,
    ["TPLobbyIfPlayer"] = true,
    ["SelectMap"] = "Egg Island",
    ["AutoVoteDifficulty"] = "true",
    ["SelectDifficulty"] = "Nightmare",
    ["SelectMacro"] = "MacroEggNGS",
    ["AutoSkip"] = true,
    ["DeleteMap"] = true,
    ["PlayMacro"] = true,
    ["AutoSave"] = true,
    ["BoostFPS"] = true,
    ["AutoClaimQuest"] = true,
    ["AutoClaimEasterQuest"] = true,
    ["AutoClaimEventsPass"] = true,
    ["AutoClaimVIPRewards"] = true,
    ["WhiteScreen"] = false,
    ["DelayJoin"] = "30",
    ["PlacingFailsafe"] = true,
    ["ExchangeTier"] = "3",
    ["AutoExchangeEgg"] = "true",
    ["MailName"] = "",
    ["RequiredGem"] = 1000,
    ["AutoMail"] = true,
    ["WH_MatchComplete"] = true,
    ["AutoUseBoost"] = true,
    ["UseBoosts"] = {
        ["2xCoinsBoost"] = true,
        ["2xEggsBoost"] = true,
    },
    ["UseAll"] = false,
    ["WebhookURL"] = "",
}
loadstring(game:HttpGet("https://nousigi.com/loader.lua"))()
